/* rrivrust - rriv board service library */

#ifndef RRIVRUST_H
#define RRIVRUST_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Unsafe FFI method that initializes the `CommandService` and returns a raw pointer to it.
 */
void *command_service_init(void);

/**
 * Unsafe FFI method that registers a command with the `CommandService` and returns a raw pointer to it.
 */
void *command_service_register_command(void *command_service_ptr,
                                       const char *object,
                                       const char *action,
                                       void (*ffi_cb)(const char*));

/**
 * Unsafe FFI method that runs the `CommandService`'s run loop iteration.
 * This should be called in the main loop of the application that is using the `CommandService`.
 */
void *command_service_run_loop_iteration(void *command_service_ptr);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* RRIVRUST_H */
