/* This is a very basic example header file */

#ifndef rust_serial_h
#define rust_serial_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

typedef struct SerialInterfaceContext SerialInterfaceContext;

struct SerialInterfaceContext *rust_serial_interface_new(void);

uint8_t rust_serial_read(struct SerialInterfaceContext *serial_ptr);

void rust_serial_write(struct SerialInterfaceContext *serial_ptr, uint8_t value);

#endif /* rust_serial_h */
