/* This is a very basic example header file */

#ifndef rust_serial_h
#define rust_serial_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void *rust_serial_interface_new(void);

uint8_t rust_serial_read(void *serial_ptr);

void rust_serial_write(void *serial_ptr, uint8_t value);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* rust_serial_h */
