/* automatically generated by rust-bindgen 0.66.1 */

pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::core::ffi::c_longlong;
pub type uintmax_t = ::core::ffi::c_ulonglong;
extern "C" {
    #[doc = " Unsafe FFI method that initializes the `CommandService` and returns a raw pointer to it."]
    pub fn command_service_init() -> *mut ::core::ffi::c_void;
}
extern "C" {
    #[doc = " Unsafe FFI method that registers a command with the `CommandService` and returns a raw pointer to it."]
    pub fn command_service_register_command(
        command_service_ptr: *mut ::core::ffi::c_void,
        object: *const ::core::ffi::c_char,
        action: *const ::core::ffi::c_char,
        ffi_cb: ::core::option::Option<unsafe extern "C" fn(arg1: *const ::core::ffi::c_char)>,
    ) -> *mut ::core::ffi::c_void;
}
extern "C" {
    #[doc = " Unsafe FFI method that runs the `CommandService`'s run loop iteration.\n This should be called in the main loop of the application that is using the `CommandService`."]
    pub fn command_service_run_loop_iteration(
        command_service_ptr: *mut ::core::ffi::c_void,
    ) -> *mut ::core::ffi::c_void;
}
