/* This is a very basic example header file */

#ifndef rust_serial_h
#define rust_serial_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

#endif /* rust_serial_h */
