/* This is a very basic example header file */

#ifndef rust_serial_h
#define rust_serial_h

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void rust_serial_interface_new(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* rust_serial_h */
